### ISSUE TITLE
Any particular instructions to pool multiple gpu's ? 

### ISSUE THREAD

**Issue by saimarpaka** [Juice-Labs/Juice-Labs#13]
Hi,
As a home user, just to test out some inference and large models, i have 2 gpu's lying around, but in different form factors (one in desktop, one in a laptop). Is there a way for this driver abstraction to use both of these gpu's?

**Comment by saimarpaka** [comment]
looks like the faq says that its in dev : "Yes, watch this space for imminent developments!"

**Comment by onlineapps-cloud** [comment]
https://github.com/Juice-Labs/Juice-Labs/wiki/Multi-GPU-Support
